depends:
    - cmp
    - cmp_mem_access:
        fork: Stapelzeiger
    - test-runner
    - serial-datagram:
        fork: Stapelzeiger

source:
    - service_call.c

tests:
    - tests/test_service_call.cpp

